--Trigger to encrypt password for new account

CREATE TRIGGER PasswordEncrption
ON Account
FOR INSERT
AS
BEGIN

OPEN SYMMETRIC KEY LMS_PASSWORDKEY
DECRYPTION BY CERTIFICATE Password_Certificate;  

UPDATE ACCOUNT SET
EncryptedPassword = ENCRYPTBYKEY(KEY_GUID('LMS_PASSWORDKEY'), [PASSWORD])
from dbo.ACCOUNT

CLOSE SYMMETRIC KEY LMS_PASSWORDKEY;	
END